# Travis-CI configuration file for SuperTuxKart modified by CandyFace for Pencil2D
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#
# How to use TravisCI with C++ (Qt Test, C++11):
# https://github.com/richelbilderbeek/travis_qmake_gcc_cpp11_qt_qtests
#
language: cpp
compiler: g++
dist: trusty
osx_image: xcode12

os:
  - linux
  - osx

jobs:
  include:
    - name: Documentation Update
      if: type != pull_request AND branch = master AND env(GH_REPO_TOKEN) IS present
      os: linux
      addons:
        apt:
          - doxygen
          - graphviz
      before_install: skip
      install: skip
      before_script: skip
      script: util/documentation-deploy.sh pencil2d/pencil-docs
      after_success: skip

env:
  global:
    - MAKEFLAGS: -j2

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - ubuntu-sdk-team
      - trusty-media
      - sourceline: 'ppa:beineri/opt-qt597-trusty'
    packages:
      - build-essential
      - qt59tools
      - qt59base
      - qt59multimedia
      - qt59svg
      - qt59xmlpatterns
      - bsdtar
      - ffmpeg
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-alsa
      - gstreamer1.0-pulseaudio
      - python3
      - python3-pip
  homebrew:
    packages:
    - qt
    - python3
    - libarchive
    - gpg

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        brew link qt --force;
        export PATH="/usr/local/opt/libarchive/bin:$PATH"
    fi

install:
  - pip3 freeze > requirements.txt
  - pip3 install -r requirements.txt
  - sudo pip3 install --upgrade typing
  - sudo pip3 install --upgrade oauth2client
  - sudo pip3 install --upgrade google-api-python-client 'setuptools<44'
  - python3 --version

before_script:
  - 'if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    . /opt/qt59/bin/qt59-env.sh;
    export DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    echo "give xvfb some time to start";
    sleep 3;
  fi'
  - qmake --version

script:
  - mkdir "build" && cd build
  - 'if [ "$TRAVIS_BRANCH" == "release" ]; then
    qmake ../ PREFIX=/usr CONFIG+=release CONFIG+=GIT CONFIG+=PENCIL2D_RELEASE;
  else
    qmake ../ PREFIX=/usr CONFIG+=release CONFIG+=GIT CONFIG+=PENCIL2D_NIGHTLY;
  fi'
  - make;
  - "$TRAVIS_BUILD_DIR/build/tests/bin/tests"

after_success:
  - "${TRAVIS_BUILD_DIR}/util/after-build.sh"
