image: Visual Studio 2019
configuration:
  - Release

environment:
  MSBUILD_FLAGS: /verbosity:minimal
  matrix:

    # MSVC x86
    - platform:   x86
      qt:         5.12.5\msvc2017
      PYTHON:     "C:\\Python35"
      PLATFORM_: "x86"

    # MSVC x64
    - platform:   amd64
      qt:         5.12.5\msvc2017_64
      PYTHON:     "C:\\Python35"
      PLATFORM_: "amd64"

skip_commits:
  files:
    - '*.md'
    - docs/*

install:
  - set PYTHON3="%PYTHON%\python.exe"
  - set UseEnv=true
  - "%PYTHON3% -m pip freeze > requirements.txt"
  - "%PYTHON3% -m pip install -r requirements.txt"
  - "%PYTHON3% -m pip install setuptools"
  - "%PYTHON3% -m pip install virtualenvwrapper"
  - "%PYTHON3% -m pip install --upgrade oauth2client"
  - "%PYTHON3% -m pip install --upgrade google-api-python-client"
  - "%PYTHON3%  -V"
  - set QTDIR=C:\Qt\%qt%
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

before_build:
  - echo %PLATFORM_%
  - echo %APPVEYOR_BUILD_FOLDER%
  - qmake --version
  - md build
  - cd build
  - if %PLATFORM_%==x86   call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
  - if %PLATFORM_%==amd64 call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if NOT %APPVEYOR_REPO_BRANCH%==release call qmake "%APPVEYOR_BUILD_FOLDER%\pencil2d.pro" CONFIG+=GIT CONFIG+=Release CONFIG+=PENCIL2D_NIGHTLY 
  - if %APPVEYOR_REPO_BRANCH%==release     call qmake "%APPVEYOR_BUILD_FOLDER%\pencil2d.pro" CONFIG+=GIT CONFIG+=Release CONFIG+=PENCIL2D_RELEASE

build_script:
  - nmake

after_build:
  - set upload=no
  - if %APPVEYOR_REPO_BRANCH%==master set upload=yes
  - if %APPVEYOR_REPO_BRANCH%==release set upload=yes
  - if "%FORCE_NIGHTLY_UPLOAD%"=="yes" set upload=yes
  - powershell ..\util\after-build.ps1 -upload %upload% -platform %PLATFORM_% -branch %APPVEYOR_REPO_BRANCH%
